### ISSUE TITLE
is it support directed graph?

### ISSUE THREAD

**Issue by zkeykyb** [louisabraham/fastnode2vec#16]
when i set directed=true ,it will support error:

```
Training:   0%|          | 0/63010 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\developer_tools\Anaconda3\envs\py3.7\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\developer_tools\Anaconda3\envs\py3.7\lib\site-packages\gensim\models\word2vec.py", line 1162, in _worker_loop
    tally, raw_tally = self._do_train_job(data_iterable, alpha, thread_private_mem)
  File "D:\developer_tools\pycharm\pycharmProject\fastnode2vec\node2vec.py", line 91, in _do_train_job
    sentences = [self.generate_random_walk(w[0]) for w in sentences]
  File "D:\developer_tools\pycharm\pycharmProject\fastnode2vec\node2vec.py", line 91, in <listcomp>
    sentences = [self.generate_random_walk(w[0]) for w in sentences]
  File "D:\developer_tools\pycharm\pycharmProject\fastnode2vec\node2vec.py", line 86, in generate_random_walk
    return self.graph.generate_random_walk(self.walk_length, self.p, self.q, t)
  File "D:\developer_tools\pycharm\pycharmProject\fastnode2vec\build_graph.py", line 157, in generate_random_walk
    walk = _random_walk(self.indptr, self.indices, walk_length, p, q, start)
ValueError: empty range for randrange()
Exception in thread Thread-7:
Traceback (most recent call last):
  File "D:\developer_tools\Anaconda3\envs\py3.7\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\developer_tools\Anaconda3\envs\py3.7\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\developer_tools\Anaconda3\envs\py3.7\lib\site-packages\gensim\models\word2vec.py", line 1162, in _worker_loop
    tally, raw_tally = self._do_train_job(data_iterable, alpha, thread_private_mem)
  File "D:\developer_tools\pycharm\pycharmProject\fastnode2vec\node2vec.py", line 91, in _do_train_job
    sentences = [self.generate_random_walk(w[0]) for w in sentences]
  File "D:\developer_tools\pycharm\pycharmProject\fastnode2vec\node2vec.py", line 91, in <listcomp>
    sentences = [self.generate_random_walk(w[0]) for w in sentences]
  File "D:\developer_tools\pycharm\pycharmProject\fastnode2vec\node2vec.py", line 86, in generate_random_walk
    return self.graph.generate_random_walk(self.walk_length, self.p, self.q, t)
  File "D:\developer_tools\pycharm\pycharmProject\fastnode2vec\build_graph.py", line 157, in generate_random_walk
    walk = _random_walk(self.indptr, self.indices, walk_length, p, q, start)
ValueError: empty range for randrange()
```

**Comment by louisabraham** [comment]
Congrats you found a bug!
Looks like you have a "sink" node with no outgoing edges. Will try to fix asap

**Comment by zkeykyb** [comment]
Thanks for your fast reply!  Yes, some nodes just have input edges, no output edges.

**Comment by louisabraham** [comment]
I tested it with the following code:


```
from fastnode2vec import Graph, Node2Vec

graph = Graph([("a", "b"), ("b", "c"), ("c", "a"), ("a", "d")],
              directed=False, weighted=False)
n2v = Node2Vec(graph, dim=10, walk_length=100, context=10, p=2.0, q=0.5, workers=2)
n2v.train(epochs=100)
print(n2v.wv["a"])
```
